### ISSUE TITLE
Random MainActivity crash

### ISSUE THREAD

**Issue by joaophellip** [joaophellip/MVP#25]
Main activity is crashing at random with the following stack trace:

```
2018-11-01 18:10:59.305 27727-27727/com.cozo.cozomvp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.cozo.cozomvp, PID: 27727
    java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.cozo.cozomvp.mainactivity.listfragment.recyclerview.RestaurantRecyclerViewAdapter.currentRestID(RestaurantRecyclerViewAdapter.kt:47)
        at com.cozo.cozomvp.mainactivity.listfragment.LocalListFragment.onRestaurantCardViewSwiped(LocalListFragment.kt:184)
        at com.cozo.cozomvp.mainactivity.listfragment.recyclerview.SwipeController.clearView(SwipeController.kt:43)
        at android.support.v7.widget.helper.ItemTouchHelper$3.onAnimationEnd(ItemTouchHelper.java:625)
        at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:552)
        at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1209)
        at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1449)
        at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
        at android.animation.AnimationHandler.-wrap2(Unknown Source:0)
        at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:655)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

```

**Comment by joaophellip** [comment]
fixed behavior inside ListFragment of when swipe is performed on the recycler view. For swipe on items from same restaurant and on items from different restaurants, main activity listener is called as if it was a click. For now, main acitivty listener isn't called when delivery partner is swiped.
